### ISSUE TITLE
[Nimrod/K] A CHECK constraint failed (CHECK constraint failed: nimrod_jobs)

### ISSUE THREAD

**Issue by vs49688** [UQ-RCC/nimrodg#11]
When running in Nimrod/K with
```
parameters = {"x", "y"}
jobs = {"x"=0, "y"=0}
```
throws the exception:
```
ptolemy.kernel.util.IllegalActionException: [SQLITE_CONSTRAINT_CHECK]  A CHECK constraint failed (CHECK constraint failed: nimrod_jobs)
  with tag colour {NOCOLOUR}
  in .Unnamed1.Nimrod/G Actor
Because:
[SQLITE_CONSTRAINT_CHECK]  A CHECK constraint failed (CHECK constraint failed: nimrod_jobs)
	at org.monash.nimrod.NimrodDirector.NimrodProcessThread.run(NimrodProcessThread.java:575)
Caused by: au.edu.uq.rcc.nimrodg.impl.base.db.NimrodSQLException: [SQLITE_CONSTRAINT_CHECK]  A CHECK constraint failed (CHECK constraint failed: nimrod_jobs)
	at au.edu.uq.rcc.nimrodg.impl.sqlite3.SQLite3DB.makeException(SQLite3DB.java:540)
	at au.edu.uq.rcc.nimrodg.impl.sqlite3.SQLite3DB.makeException(SQLite3DB.java:67)
	at au.edu.uq.rcc.nimrodg.impl.base.db.SQLUUUUU.runSQLTransaction(SQLUUUUU.java:65)
	at au.edu.uq.rcc.nimrodg.impl.base.db.TempNimrodAPIImpl.addJobs(TempNimrodAPIImpl.java:124)
	at au.edu.uq.rcc.nimrodg.impl.base.db.TempNimrodAPIImpl.addJobs(TempNimrodAPIImpl.java:58)
	at au.edu.uq.rcc.nimrod.NimrodGActor.fire(NimrodGActor.java:340)
	at org.monash.nimrod.NimrodDirector.NimrodProcessThread.run(NimrodProcessThread.java:464)
Caused by: au.edu.uq.rcc.nimrodg.impl.base.db.NimrodSQLException: [SQLITE_CONSTRAINT_CHECK]  A CHECK constraint failed (CHECK constraint failed: nimrod_jobs)
	at au.edu.uq.rcc.nimrodg.impl.sqlite3.SQLite3DB.makeException(SQLite3DB.java:540)
	at au.edu.uq.rcc.nimrodg.impl.sqlite3.SQLite3DB.makeException(SQLite3DB.java:67)
	at au.edu.uq.rcc.nimrodg.impl.base.db.SQLUUUUU.runSQLTransaction(SQLUUUUU.java:65)
	at au.edu.uq.rcc.nimrodg.impl.base.db.TempNimrodAPIImpl.addJobs(TempNimrodAPIImpl.java:124)
	at au.edu.uq.rcc.nimrodg.impl.base.db.TempNimrodAPIImpl.addJobs(TempNimrodAPIImpl.java:58)
	at au.edu.uq.rcc.nimrod.NimrodGActor.fire(NimrodGActor.java:340)
	at org.monash.nimrod.NimrodDirector.NimrodProcessThread.run(NimrodProcessThread.java:464)

```

**Comment by vs49688** [comment]
Closed by a39654269746418305d5bae709f325c4424230e8
