### ISSUE TITLE
"no schema has been selected to create in" when using currentSchema in JDBC URL

### ISSUE THREAD

**Issue by vs49688** [UQ-RCC/nimrodg#35]
```
$ nimrod setup init
au.edu.uq.rcc.nimrodg.setup.NimrodSetupAPI$SetupException: org.postgresql.util.PSQLException: ERROR: no schema has been selected to create in
	at au.edu.uq.rcc.nimrodg.impl.postgres.SetupAPIImpl.reset(SetupAPIImpl.java:144)
	at au.edu.uq.rcc.nimrodg.cli.commands.Setup.execute(Setup.java:110)
	at au.edu.uq.rcc.nimrodg.cli.DefaultCLICommand.execute(DefaultCLICommand.java:36)
	at au.edu.uq.rcc.nimrodg.cli.NimrodCLI.cliMain(NimrodCLI.java:125)
	at au.edu.uq.rcc.nimrodg.cli.NimrodCLI.main(NimrodCLI.java:145)
Caused by: org.postgresql.util.PSQLException: ERROR: no schema has been selected to create in
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2422)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2167)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at au.edu.uq.rcc.nimrodg.impl.postgres.SetupAPIImpl.reset(SetupAPIImpl.java:142)
```

**Comment by vs49688** [comment]
Not a bug, cause by bad schema permissions. For reference:
```
CREATE SCHEMA schema;
ALTER SCHEMA schema OWNER TO user;
```
